
/* VPNSTAN v26 multilingual UI */
const I18N={
 fa:{dir:'rtl',title:'نمای کلی',sub:'مدیریت سرویس vpnstan · نسخه v26',badgeMaster:'پنل مادر',logout:'خروج',overview:'نمای کلی',clients:'کلاینت‌ها',configs:'کانفیگ‌ها',subscriptions:'اشتراک‌ها',dns:'DNS',settings:'تنظیمات',telegram:'ربات تلگرام',account:'حساب من',admin:'مدیریت پنل‌ها',online:'سرویس آنلاین',login:'ورود به پنل',loginDesc:'مدیریت مستقل کانفیگ‌ها، اشتراک‌ها و پنل‌های فرزند',username:'نام کاربری',password:'رمز عبور'},
 en:{dir:'ltr',title:'Overview',sub:'vpnstan service management · v26',badgeMaster:'Master Panel',logout:'Logout',overview:'Overview',clients:'Clients',configs:'Configs',subscriptions:'Subscriptions',dns:'DNS',settings:'Settings',account:'My Account',admin:'Panel Management',online:'Service Online',login:'Sign in',loginDesc:'Independent management of configs, subscriptions and child panels',username:'Username',password:'Password'}
};

const STATIC_I18N={
'داشبورد':['Dashboard','داشبورد'],'کاربران':['Users','کاربران'],'ساخت کانفیگ':['Create Config','ساخت کانفیگ'],'مدیریت کانفیگ‌ها':['Config Management','مدیریت کانفیگ‌ها'],'لینک‌های ساب':['Subscriptions','لینک‌های ساب'],'DNS':['DNS','DNS'],'تنظیمات':['Settings','تنظیمات'],'حساب من':['My Account','حساب من'],'مدیریت پنل':['Panel Management','مدیریت پنل'],'مدیریت پنل‌ها':['Panel Management','مدیریت پنل‌ها'],'سرویس آنلاین':['Service Online','سرویس آنلاین'],
'VPNSTAN · DASHBOARD':['VPNSTAN · DASHBOARD','VPNSTAN · DASHBOARD'],'VPNSTAN · SUBSCRIPTIONS':['VPNSTAN · SUBSCRIPTIONS','VPNSTAN · SUBSCRIPTIONS'],'عملیات سریع':['Quick Actions','عملیات سریع'],'آمار مصرف ترافیک':['Traffic Usage','آمار مصرف ترافیک'],'نمایش مصرف فعلی کانفیگ‌ها':['Current configuration traffic usage','نمایش مصرف فعلی کانفیگ‌ها'],'مصرف کل ترافیک':['Total Traffic Usage','مصرف کل ترافیک'],'بر اساس کل کانفیگ‌ها':['Based on all configurations','بر اساس کل کانفیگ‌ها'],'مصرف':['Usage','مصرف'],'مصرف شده':['Used','مصرف شده'],'کل کاربران':['Total Users','کل کاربران'],'کل کانفیگ‌ها':['Total Configs','کل کانفیگ‌ها'],'لینک‌های ساب':['Subscriptions','لینک‌های ساب'],'وضعیت سرور':['Server Status','وضعیت سرور'],'آنلاین':['Online','آنلاین'],'موقعیت سرور':['Server Location','موقعیت سرور'],'آی‌پی سرور':['Server IP','آی‌پی سرور'],'نوع اتصال':['Connection Type','نوع اتصال'],'پنل مادر':['Master Panel','پنل مادر'],
'تنظیمات پنل':['Panel Settings','تنظیمات پنل'],'مدیریت تنظیمات vpnstan':['Manage vpnstan settings','مدیریت تنظیمات vpnstan'],'ساخت کانفیگ و لینک‌ها':['Create configs and links','ساخت کانفیگ و لینک‌ها'],'ساخت و مدیریت کاربران سرویس':['Create and manage service users','ساخت و مدیریت کاربران سرویس'],'ساخت پنل‌های فرزند روی همین سرویس':['Create child panels on this service','ساخت پنل‌های فرزند روی همین سرویس'],'ایجاد لینک اشتراک جدید':['Create new subscription link','ایجاد لینک اشتراک جدید'],'لینک هر اشتراک را مستقیم کپی یا مدیریت کنید.':['Copy or manage each subscription link directly.','لینک هر اشتراک را مستقیم کپی یا مدیریت کنید.'],
'حجم مصرفی پنل':['Panel Usage','حجم مصرفی پنل'],'حجم پنل':['Panel Usage','حجم پنل'],'حساب من':['My Account','حساب من'],'تغییر اکانت':['Switch Account','تغییر اکانت'],'خروج از پنل':['Sign out','خروج از پنل'],'ادمین':['Admin','ادمین'],'کاربر پنل':['Panel User','کاربر پنل'],'نام کاربری':['Username','نام کاربری'],'رمز عبور':['Password','رمز عبور'],'ورود به پنل':['Sign in','ورود به پنل'],'مدیریت مستقل کانفیگ‌ها، اشتراک‌ها و پنل‌های فرزند':['Independent management of configs, subscriptions and child panels','مدیریت مستقل کانفیگ‌ها، اشتراک‌ها و پنل‌های فرزند'],
'ساخت کانفیگ جدید':['Create New Config','ساخت کانفیگ جدید'],'ساخت کلاینت':['Create Client','ساخت کلاینت'],'لیست کلاینت‌ها':['Client List','لیست کلاینت‌ها'],'ساخت لینک ساب':['Create Subscription','ساخت لینک ساب'],'اشتراک‌های سرویس':['Service Subscriptions','اشتراک‌های سرویس'],'Subscription های شما':['Your Subscriptions','Subscription های شما'],'کل اشتراک‌ها':['Total Subscriptions','کل اشتراک‌ها'],'اشتراک فعال':['Active Subscription','اشتراک فعال'],'زنده':['Live','زنده'],'بروزرسانی':['Refresh','بروزرسانی'],'ویرایش کانفیگ':['Edit Config','ویرایش کانفیگ'],'حذف کانفیگ':['Delete Config','حذف کانفیگ'],'ذخیره تغییرات':['Save Changes','ذخیره تغییرات'],'ذخیره تنظیمات':['Save Settings','ذخیره تنظیمات'],'ذخیره اطلاعات ورود':['Save login information','ذخیره اطلاعات ورود'],'انصراف':['Cancel','انصراف'],'افزودن کاربر':['Add User','افزودن کاربر'],'کاربر جدید اضافه کنید':['Add a new user','کاربر جدید اضافه کنید'],'ساخت پنل فرزند':['Create Child Panel','ساخت پنل فرزند'],'دسترسی‌های پنل':['Panel Permissions','دسترسی‌های پنل'],'دسترسی تنظیمات':['Settings Access','دسترسی تنظیمات'],
'نام کلاینت':['Client Name','نام کلاینت'],'حجم (GB)':['Traffic (GB)','حجم (GB)'],'حجم هر کانفیگ (GB)':['Traffic per Config (GB)','حجم هر کانفیگ (GB)'],'اعتبار (روز)':['Validity (days)','اعتبار (روز)'],'اعتبار هر کانفیگ (روز)':['Validity per Config (days)','اعتبار هر کانفیگ (روز)'],'تعداد کانفیگ در یک ساب':['Configs per Subscription','تعداد کانفیگ در یک ساب'],'پروتکل':['Protocol','پروتکل'],'Transport':['Transport','Transport'],'تنظیم خودکار':['Auto','تنظیم خودکار'],'تم پنل':['Panel Theme','تم پنل'],'تنظیمات نود و خروجی اشتراک':['Node and Subscription Output Settings','تنظیمات نود و خروجی اشتراک'],'دامنه / Host نود':['Node Domain / Host','دامنه / Host نود'],'پورت اتصال':['Connection Port','پورت اتصال'],'مسیر VLESS WebSocket':['VLESS WebSocket Path','مسیر VLESS WebSocket'],'مسیر VMess WebSocket':['VMess WebSocket Path','مسیر VMess WebSocket'],'مسیر Subscription':['Subscription Path','مسیر Subscription'],'عنوان اشتراک':['Subscription Title','عنوان اشتراک'],'لینک پشتیبانی':['Support Link','لینک پشتیبانی'],'WireGuard Endpoint':['WireGuard Endpoint','WireGuard Endpoint'],'WireGuard Server Public Key':['WireGuard Server Public Key','WireGuard Server Public Key'],
'ذخیره تغییرات':['Save Changes','ذخیره تغییرات'],'تغییر نام کاربری و رمز عبور ورود به پنل':['Change panel login username and password','تغییر نام کاربری و رمز عبور ورود به پنل'],'رمز فعلی':['Current Password','رمز فعلی'],'رمز جدید':['New Password','رمز جدید'],'نام کاربری جدید':['New Username','نام کاربری جدید'],'اکانت‌های ورود قدیمی':['Legacy Login Accounts','اکانت‌های ورود قدیمی'],'IP تشخیص‌داده‌شده':['Detected IP','IP تشخیص‌داده‌شده'],'IP مجاز (اختیاری)':['Allowed IP (optional)','IP مجاز (اختیاری)'],'برای پنل جدید هنگام ساخت ذخیره می‌شود.':['Saved for the new panel when it is created.','برای پنل جدید هنگام ساخت ذخیره می‌شود.'],'نیازی به ورود تنظیمات اضافه نیست.':['No additional settings are required.','نیازی به ورود تنظیمات اضافه نیست.']
};
function translateStatic(){
 const en=currentLang==='en';
 const walker=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT);
 const nodes=[]; while(walker.nextNode()) nodes.push(walker.currentNode);
 nodes.forEach(n=>{if(!n.parentElement||['SCRIPT','STYLE','OPTION'].includes(n.parentElement.tagName))return;const raw=n.nodeValue;const key=raw.trim();const pair=STATIC_I18N[key];if(pair){const val=pair[en?0:1];n.nodeValue=raw.replace(key,val)}});
 document.querySelectorAll('option').forEach(o=>{if(o.value==='fa')o.textContent=en?'Persian':'فارسی';if(o.value==='en')o.textContent=en?'English':'English'});
 const btn=document.querySelector('#login .btn.primary');if(btn)btn.textContent=en?'Sign in':'ورود به پنل';
 const quick=document.querySelectorAll('.quick-card');
 if(quick.length){const labels=en?['Panel Settings','Create Config','Add User','Create Subscription']:['تنظیمات پنل','ساخت کانفیگ','افزودن کاربر','ساخت لینک ساب'];quick.forEach((q,i)=>{const b=q.querySelector('b');if(b&&labels[i])b.textContent=labels[i]})}
}

let currentLang=localStorage.getItem('vpnstan_lang')||'fa';
function setLanguage(lang){currentLang=lang==='en'?'en':'fa';localStorage.setItem('vpnstan_lang',currentLang);document.documentElement.lang=currentLang;document.documentElement.dir=I18N[currentLang].dir;const t=I18N[currentLang];
 const set=(sel,key)=>{const e=document.querySelector(sel);if(e)e.textContent=t[key]};
 set('#title','title');set('header small','sub');set('#currentPanelBadge','badgeMaster');
 const navMap={dashboard:'overview',clients:'clients',configs:'configs',subscriptions:'subscriptions',dns:'dns',settings:'settings',account:'account',admin:'admin'};
document.querySelectorAll('.nav[data-tab]').forEach(n=>{const k=navMap[n.dataset.tab]; if(k){const label=n.querySelector('.nav-label'); if(label) label.textContent=t[k]; const small=n.querySelector('small'); if(small) small.textContent=n.dataset.tab==='dashboard'?'Overview':'';}});
 const logout=document.querySelector('button[onclick="logout()"]');if(logout)logout.textContent=t.logout;
 const loginTitle=document.querySelector('#login h1');if(loginTitle)loginTitle.textContent=t.login;
 const loginP=document.querySelector('#login p');if(loginP)loginP.textContent=t.loginDesc;
 const u=document.querySelector('#username');if(u)u.placeholder=t.username; const p=document.querySelector('#password');if(p)p.placeholder=t.password;
 const ls=document.querySelector('#langSelect');if(ls)ls.value=currentLang;
 document.querySelectorAll('.login-lang button').forEach(b=>b.textContent=currentLang==='fa'?'🌐 فارسی / English':'🌐 English / فارسی');
 translateStatic();
 // Keep form controls and API behavior intact; translate only stable labels/placeholders.
 const labels={
 '#name':['نام کلاینت','Client name'],'#gb':['حجم هر کانفیگ (GB)','Traffic per config (GB)'],'#days':['اعتبار هر کانفیگ (روز)','Validity (days)'],'#subCount':['تعداد کانفیگ در یک ساب','Configs per subscription'],
 '#setHost':['دامنه / Host نود','Node domain / Host'],'#setPort':['پورت اتصال','Connection port'],'#setPath':['مسیر VLESS WebSocket','VLESS WebSocket path'],'#setVmessPath':['مسیر VMess WebSocket','VMess WebSocket path'],'#setSub':['مسیر Subscription','Subscription path'],'#setTitle':['عنوان اشتراک','Subscription title'],'#setSupport':['لینک پشتیبانی','Support link'],'#setWgEndpoint':['WireGuard Endpoint','WireGuard Endpoint'],'#setWgKey':['WireGuard Server Public Key','WireGuard Server Public Key']};
 Object.entries(labels).forEach(([sel,v])=>{const e=document.querySelector(sel);if(e){e.placeholder=v[currentLang==='fa'?0:1]||e.placeholder;const l=e.previousElementSibling;if(l&&l.tagName==='LABEL')l.textContent=v[currentLang==='fa'?0:1]}});
}
window.addEventListener('DOMContentLoaded',()=>{const ls=document.getElementById('langSelect');if(ls)ls.addEventListener('change',e=>setLanguage(e.target.value));setLanguage(currentLang)});

const $=id=>document.getElementById(id);let clients=[],settings={},me=null;
function applyTheme(t){t=t||'dark';document.documentElement.setAttribute('data-theme',t);localStorage.setItem('vpnstan_theme',t);if($('setTheme'))$('setTheme').value=t}
applyTheme(localStorage.getItem('vpnstan_theme')||'dark');
async function req(u,o={}){let r=await fetch(u,{credentials:'include',...o});let d;try{d=await r.json()}catch{d={msg:'خطای پاسخ سرور'}}if(!r.ok)throw Error(d.msg||'خطا');return d}
const titles={dashboard:'نمای کلی',clients:'کلاینت‌ها',configs:'کانفیگ‌ها',subscriptions:'اشتراک‌ها',dns:'DNS',settings:'تنظیمات',telegram:'ربات تلگرام',account:'حساب من',admin:'مدیریت پنل‌ها'};
function can(p){return !me||me.role==='admin'||me.panel_id===0||p==='overview'||p==='account'||me.permissions?.[p]}
function applyPermissions(){document.querySelectorAll('.nav[data-perm]').forEach(n=>{const p=n.dataset.perm;let hide=false;if(p==='admin')hide=!(me?.role==='admin');else if(p==='telegram')hide=!(me?.role==='admin');else hide=!can(p);n.classList.toggle('hidden',hide)});if(me?.role==='admin'){document.getElementById('adminNav').classList.remove('hidden');$('telegramNav')?.classList.remove('hidden');$('masterOverview').classList.remove('hidden')}else{$('masterOverview').classList.add('hidden')}$('currentPanelBadge').textContent='v26';if($('headerUser'))$('headerUser').textContent=me?.username||'admin';if($('dropUsername'))$('dropUsername').textContent=me?.username||'admin';if($('dropRole'))$('dropRole').textContent=me?.role==='admin'?'مدیر / ادمین':'کاربر پنل'}
function openTab(id){const section=$(id);if(!section)return;const nav=document.querySelector(`.nav[data-tab="${id}"]`);if(nav&&nav.classList.contains('hidden'))return;document.querySelectorAll('.tab').forEach(x=>x.classList.add('hidden'));section.classList.remove('hidden');document.querySelectorAll('.nav').forEach(x=>x.classList.toggle('active',x.dataset.tab===id));$('title').textContent=titles[id]||id;if(id==='clients')renderClients();if(id==='configs')renderConfigs();if(id==='subscriptions')renderSubs();if(id==='dns')renderDns();if(id==='settings')loadSettings();if(id==='telegram')loadTelegram();if(id==='account')loadMe();if(id==='admin')loadPanels()}
document.querySelectorAll('.nav').forEach(x=>x.addEventListener('click',()=>openTab(x.dataset.tab)));
window.addEventListener('error',e=>{const el=$('loginMsg')||$('createMsg');if(el&&!e.message.includes('Script error'))el.textContent='خطای رابط پنل: '+e.message});
function updateProtocolFields(){const p=$('protocol')?.value;const f=$('dnsField');const tr=$('transport');const tl=$('transportLabel');if(f){f.classList.add('hidden');f.innerHTML=''}if(tr){tr.disabled=(p==='wireguard'||p==='dns');if(tr.disabled)tr.value='ws'}if(tl)tl.classList.toggle('hidden',p==='wireguard'||p==='dns');const note=$('createMsg');if(note&&p==='dns')note.textContent='برای این کاربر یک DNS اختصاصی DoH با حجم و اعتبار جداگانه ساخته می‌شود.';else if(note&&note.textContent.includes('DNS اختصاصی'))note.textContent=''}
$('protocol')?.addEventListener('change',updateProtocolFields);window.addEventListener('DOMContentLoaded',updateProtocolFields);

async function login(){try{let d=await req('/api/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:$('username').value,password:$('password').value})});if(!d.success)throw Error(d.msg);showApp()}catch(e){$('loginMsg').textContent=e.message}}
let liveRefreshTimer=null;async function showApp(){$('login').classList.add('hidden');$('app').classList.remove('hidden');await loadMe();await loadSettings();await refresh();if(!liveRefreshTimer)liveRefreshTimer=setInterval(()=>refresh(),10000)}
async function refresh(){try{let d=await req('/api/clients');clients=d.clients;const active=clients.filter(x=>x.enabled&&!expired(x)).length;$('count').textContent=clients.length;$('active').textContent=active;$('expired').textContent=clients.filter(expired).length;if($('configCount'))$('configCount').textContent=clients.length;if($('subCountDash'))$('subCountDash').textContent=new Set(clients.map(x=>x.subId||x.subscription||x.id)).size;const total=clients.reduce((n,x)=>n+Number(x.totalBytes||0),0),used=clients.reduce((n,x)=>n+Number(x.usedBytes||x.used||0),0),pct=total?Math.min(100,used/total*100):0;updateUserQuota(used,total);if($('usagePct'))$('usagePct').textContent=Math.round(pct)+'%';if($('usageText'))$('usageText').textContent=fmtUsed(used)+' / '+fmtUsed(total);if($('usageFill'))$('usageFill').style.width=pct+'%';if($('usageRing'))$('usageRing').style.background='conic-gradient(#2f7bff 0 '+pct+'%,#1a2d4a '+pct+'% 100%)';if($('serverIp'))$('serverIp').textContent=settings.node_host||'Railway domain';if($('serverPort'))$('serverPort').textContent=settings.node_port||443;renderClients();renderConfigs();renderSubs();renderDns();updateDash()}catch(e){if(e.message.includes('ورود'))location.reload()}}
function expired(c){return c.expiryAt&&c.expiryAt*1000<Date.now()}
async function loadMe(){try{let d=await req('/api/me');me=d.user;if(!me)return;applyPermissions();$('accUser').value=me.username;if(me.role==='admin')loadPanels()}catch{}}
function fmtUsed(n){n=Number(n||0);const u=['B','KB','MB','GB','TB'];let i=0,x=n;while(x>=1024&&i<u.length-1){x/=1024;i++}return(i>=3?x.toFixed(2):Math.round(x*100)/100)+' '+u[i]}
function renderClients(){if(!$('clientsList'))return;$('clientsList').innerHTML=clients.length?clients.map(c=>{const used=Number(c.used||0),total=Number(c.totalBytes||0),pct=total?Math.min(100,used/total*100):0,cls=pct>=95?'danger':pct>=80?'warn':'';return `<div class="client-row"><div class="client-meta"><b>${esc(c.name)}</b><small>${c.protocol.toUpperCase()} · ${(c.transport||'ws').toUpperCase()} · ${c.gb} GB · ${c.days} روز · ${expired(c)?'منقضی':(c.online?'آنلاین':'فعال')}</small></div><div class="usage"><div class="usage-top"><span>مصرف</span><strong>${esc(c.usedText||fmtUsed(used))} / ${esc(c.totalText||fmtUsed(total))} · ${pct.toFixed(1)}%</strong></div><div class="usage-bar"><div class="usage-fill ${cls}" style="width:${pct}%"></div></div></div><div class="row-actions">${can('clients_edit')?`<button class="mini" onclick="editClient(${c.id})">ویرایش</button>`:''}<button class="mini" onclick="copy('${enc(c.config)}')">کپی ${esc(c.protocol.toUpperCase())}</button>${can('configs_view')?`<button class="mini" onclick="copy('${enc(c.subscription)}')">کپی Sub</button>`:''}${can('clients_delete')?`<button class="danger mini" onclick="del(${c.id})">حذف</button>`:''}</div></div>`}).join(''):'<div class="empty">هنوز کلاینتی ساخته نشده است.</div>'}
function renderConfigs(){if(!$('configList'))return;$('configList').innerHTML=clients.length?clients.map(c=>`<div class="config-card"><div class="config-top"><div><b>${esc(c.name)}</b><span class="tag">${esc(c.protocol.toUpperCase())} · ${expired(c)?'منقضی':'فعال'}</span></div><small>${c.gb} GB · تا ${new Date(c.expiryAt*1000).toLocaleDateString('fa-IR')}</small></div><label>کانفیگ ${esc(c.protocol.toUpperCase())}</label><div class="copybox"><code>${esc(c.config)}</code><button onclick="copy('${enc(c.config)}')">کپی</button></div>${c.protocol==='dns'?`<label>DNS Subscription اختصاصی</label><div class="copybox"><code>${esc(c.dnsSubscription||'')}</code><button onclick="copy('${enc(c.dnsSubscription||'')}')">کپی</button></div><label>DNS اختصاصی DoH</label><div class="copybox"><code>${esc(c.dnsUrl||'')}</code><button onclick="copy('${enc(c.dnsUrl||'')}')">کپی</button></div>`:(c.protocol==='vless'||c.protocol==='vmess'?`<label>Subscription</label><div class="copybox"><code>${esc(c.subscription||'')}</code><button onclick="copy('${enc(c.subscription||'')}')">کپی</button></div>`:'')}<div class="config-actions">${can('clients_edit')?`<button class="mini" onclick="editClient(${c.id})">ویرایش</button>`:''}${can('clients_delete')?`<button class="danger mini" onclick="del(${c.id})">حذف</button>`:''}</div></div>`).join(''):'<div class="empty">برای نمایش کانفیگ، ابتدا یک کلاینت بسازید.</div>'}
function renderSubs(){
 if(!$('subList'))return;
 const groups={};
 clients.filter(c=>c.protocol==='vless'||c.protocol==='vmess'||c.protocol==='trojan'||c.protocol==='wireguard').forEach(c=>(groups[c.subId||c.subscription||c.id]??=[]).push(c));
 const vals=Object.entries(groups);
 const totalUsed=clients.reduce((n,c)=>n+Number(c.usedBytes||c.used||0),0);
 $('subTotalCount').textContent=vals.length;
 $('subConfigCount').textContent=clients.length;
 $('subUsageCount').textContent=fmtUsed(totalUsed);
 const activeSubs=vals.filter(([,arr])=>arr.some(c=>c.enabled&&!expired(c))).length;
 $('subActiveCount').textContent=activeSubs;
 if(!vals.length){$('subList').innerHTML='<div class="empty sub-empty"><div class="sub-empty-icon">↯</div><b>هنوز اشتراکی ساخته نشده است</b><span>اولین Subscription خود را بسازید تا لینک و وضعیت مصرف اینجا نمایش داده شود.</span><button class="btn primary" onclick="openTab(\'clients\')">ساخت اولین اشتراک</button></div>';return}
 $('subList').innerHTML=vals.map(([sid,arr],index)=>{
   const total=arr.reduce((n,c)=>n+Number(c.totalBytes||0),0),used=arr.reduce((n,c)=>n+Number(c.usedBytes||c.used||0),0),pct=total?Math.min(100,Math.round(used/total*100)):0;
   const active=arr.filter(c=>c.enabled&&!expired(c)).length;
   const expiry=Math.max(...arr.map(c=>Number(c.expiryAt||0)));
   const daysLeft=expiry?Math.max(0,Math.ceil((expiry-Date.now()/1000)/86400)):0;
   const status=active?'فعال':(daysLeft>0?'محدود':'منقضی');
   const statusClass=active?'active':(daysLeft>0?'limited':'expired');
   const sub=arr[0].subscription||'';
   const shortId=String(sid).slice(0,8).toUpperCase();
   return `<article class="pro-sub-card">
     <div class="pro-sub-top"><div class="pro-sub-title"><span class="pro-sub-icon">↯</span><div><b>${esc(arr[0].name||'VPNSTAN Subscription')}</b><small>SUB-${esc(shortId)} · ${arr.length} کانفیگ</small></div></div><span class="pro-sub-status ${statusClass}"><i></i>${status}</span></div>
     <div class="pro-sub-body">
       <div class="pro-sub-stats"><div><small>کانفیگ‌ها</small><strong>${arr.length}</strong><span>${active} فعال</span></div><div><small>مصرف شده</small><strong>${esc(fmtUsed(used))}</strong><span>از ${esc(fmtUsed(total))}</span></div><div><small>اعتبار</small><strong>${daysLeft} روز</strong><span>${daysLeft?'باقی‌مانده':'پایان یافته'}</span></div></div>
       <div class="pro-sub-progress"><div><span>مصرف اشتراک</span><b>${pct}%</b></div><div class="pro-progress-track"><i style="width:${pct}%"></i></div></div>
       <div class="pro-sub-link-label"><span>لینک Subscription</span><small>برای استفاده در کلاینت کپی کنید</small></div>
       <div class="pro-copybox"><span class="link-dot"></span><code>${esc(sub)}</code><button onclick="copy('${enc(sub)}')">کپی لینک</button></div>
       <div class="pro-sub-actions"><button class="pro-action primary-action" onclick="copy('${enc(sub)}')">⧉ کپی Subscription</button><button class="pro-action" onclick="openTab('configs')">▣ مدیریت کانفیگ‌ها</button><button class="pro-action" onclick="refresh()">↻ بروزرسانی</button></div>
       <div class="pro-sub-configs"><div class="pro-config-head"><b>کانفیگ‌های این اشتراک</b><span>${arr.length} مورد</span></div>${arr.map((c,i)=>{const cp=Number(c.totalBytes)?Math.min(100,Math.round(Number(c.usedBytes||c.used||0)/Number(c.totalBytes)*100)):0;return `<div class="pro-config-row"><span class="pro-config-num">${i+1}</span><div class="pro-config-main"><b>${esc(c.name)}</b><small>${esc(String(c.protocol||'').toUpperCase())} · ${esc(c.transport||'WS')} · ${esc(c.usedText||'0 B')} / ${esc(c.totalText||fmtUsed(c.totalBytes))}</small></div><div class="pro-mini-progress"><i style="width:${cp}%"></i></div><span class="pro-config-pct">${cp}%</span><span class="pro-config-state ${c.enabled&&!expired(c)?'on':'off'}"></span></div>`}).join('')}</div>
     </div>
   </article>`;
 }).join('');
}
async function createClient(){let name=$('name').value.trim(),gb=+$('gb').value,days=+$('days').value,protocol=$('protocol').value,transport=$('transport').value,subCount=Math.floor(+$('subCount').value||1);if(!name||gb<=0||days<=0||subCount<1||subCount>20)return $('createMsg').textContent='نام، حجم، مدت و تعداد کانفیگ را درست وارد کنید.';if(protocol==='dns'&&subCount>1)return $('createMsg').textContent='برای DNS تعداد کانفیگ در هر ساب باید 1 باشد.';try{let d=await req('/api/clients/create',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name,gb,days,protocol,transport,dnsServer:'',subCount})});$('createMsg').textContent=`${d.count||subCount} کانفیگ داخل یک ساب ساخته شد.`;$('name').value='';$('subCount').value='1';await refresh();openTab(protocol==='dns'?'dns':'subscriptions');setTimeout(()=>copy(protocol==='dns'?d.client.dnsUrl:d.client.subscription),100)}catch(e){$('createMsg').textContent=e.message||'ساخت کانفیگ انجام نشد'}}
function editClient(id){const c=clients.find(x=>Number(x.id)===Number(id));if(!c)return;$('editId').value=c.id;$('editName').value=c.name;$('editProtocol').value=c.protocol;$('editTransport').value=c.transport||'ws';$('editGb').value=c.gb;$('editDays').value=c.days;$('editMsg').textContent='';$('editModal').classList.remove('hidden')}
function closeEdit(){$('editModal').classList.add('hidden')}
async function saveEdit(){try{const id=$('editId').value;await req('/api/clients/'+id+'/edit',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:$('editName').value,protocol:$('editProtocol').value,transport:$('editTransport').value,gb:$('editGb').value,days:$('editDays').value})});$('editMsg').textContent='تغییرات ذخیره شد.';await refresh();setTimeout(closeEdit,400)}catch(e){$('editMsg').textContent=e.message}}
async function del(id){if(!confirm('این کلاینت حذف شود؟'))return;try{await req('/api/clients/'+id+'/delete',{method:'POST'});refresh()}catch(e){alert(e.message)}}
async function loadTelegram(){try{let d=await req('/api/telegram/status');$('tgEnabled').checked=!!d.enabled;$('tgAdminId').value=d.adminId||'';$('tgToken').value='';if(d.connected){$('tgStatus').innerHTML=`وضعیت: <b>متصل</b> · @${d.bot?.username||d.bot?.first_name||'bot'} · Bot ID: <code>${d.bot?.id||d.botId||'-'}</code>`;$('tgMsg').textContent=d.adminConfigured?`آیدی ادمین: ${d.adminId}`:'آیدی ادمین هنوز ثبت نشده؛ بعد از شروع ربات، /claimadmin را از داخل ربات ارسال کن.'}else{$('tgStatus').textContent=d.configured?`وضعیت: ${d.error||'تنظیم شده ولی متصل نیست'}`:'وضعیت: غیرفعال'}}catch(e){$('tgMsg').textContent=e.message}}
async function testTelegram(){try{let d=await req('/api/telegram/test',{method:'POST'});$('tgStatus').innerHTML=`وضعیت: <b>متصل</b> · @${d.bot?.username||d.bot?.first_name||'bot'} · Bot ID: <code>${d.bot?.id||d.botId||'-'}</code>`;$('tgMsg').textContent='اتصال توکن صحیح است. حالا ربات را در تلگرام باز کن و /claimadmin را بفرست.'}catch(e){$('tgMsg').textContent=e.message}}
async function saveTelegram(){try{const token=$('tgToken').value.trim();let payload={token,adminId:$('tgAdminId').value.trim(),enabled:$('tgEnabled').checked};let d=await req('/api/telegram/save',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});$('tgStatus').innerHTML=d.connected?`وضعیت: <b>متصل</b> · @${d.bot?.username||d.bot?.first_name||'bot'} · Bot ID: <code>${d.bot?.id||d.botId||'-'}</code>`:'وضعیت: غیرفعال';$('tgMsg').textContent=d.connected?(d.adminId?`ربات وصل شد. آیدی ادمین: ${d.adminId}`:'ربات وصل شد. برای ثبت خودکار آیدی ادمین، داخل ربات /claimadmin را ارسال کن.'):'ربات غیرفعال شد.'}catch(e){$('tgMsg').textContent=e.message}}
async function loadSettings(){try{let d=await req('/api/settings');settings=d.settings;$('setHost').value=settings.node_host||'';$('setPort').value=settings.node_port||443;$('setPath').value=settings.ws_path||'/ws';$('setVmessPath').value=settings.vmess_path||'/vmess';$('setXhttpPath').value=settings.xhttp_path||'/xhttp';$('setGrpcService').value=settings.grpc_service||'vpnstan';$('setGrpcPath').value=settings.grpc_path||'/grpc';$('setUpgradePath').value=settings.httpupgrade_path||'/upgrade';$('setVmessXhttpPath').value=settings.vmess_xhttp_path||'/vmess-xhttp';$('setVmessGrpcPath').value=settings.vmess_grpc_path||'/vmess-grpc';$('setVmessUpgradePath').value=settings.vmess_httpupgrade_path||'/vmess-upgrade';$('setTrojanPath').value=settings.trojan_ws_path||'/trojan';$('setTrojanXhttpPath').value=settings.trojan_xhttp_path||'/trojan-xhttp';$('setTrojanGrpcPath').value=settings.trojan_grpc_path||'/trojan-grpc';$('setTrojanUpgradePath').value=settings.trojan_httpupgrade_path||'/trojan-upgrade';$('setSub').value=settings.sub_path||'sub';$('setTitle').value=settings.panel_title||'vpnstan';$('setTheme').value=settings.theme||localStorage.getItem('vpnstan_theme')||'dark';applyTheme($('setTheme').value);$('setSupport').value=settings.support_url||'';$('setWgEndpoint').value=settings.wg_endpoint||'';$('setWgKey').value=settings.wg_server_public_key||'';updateDash()}catch(e){}}
async function saveSettings(){try{let d=await req('/api/settings',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({node_host:$('setHost').value,node_port:$('setPort').value,ws_path:$('setPath').value,vmess_path:$('setVmessPath').value,xhttp_path:$('setXhttpPath').value,grpc_service:$('setGrpcService').value,grpc_path:$('setGrpcPath').value,httpupgrade_path:$('setUpgradePath').value,vmess_xhttp_path:$('setVmessXhttpPath').value,vmess_grpc_path:$('setVmessGrpcPath').value,vmess_httpupgrade_path:$('setVmessUpgradePath').value,trojan_ws_path:$('setTrojanPath').value,trojan_xhttp_path:$('setTrojanXhttpPath').value,trojan_grpc_path:$('setTrojanGrpcPath').value,trojan_httpupgrade_path:$('setTrojanUpgradePath').value,sub_path:$('setSub').value,panel_title:$('setTitle').value,support_url:$('setSupport').value,theme:$('setTheme').value,wg_endpoint:$('setWgEndpoint').value,wg_server_public_key:$('setWgKey').value})});settings=d.settings;applyTheme(settings.theme||'dark');$('setMsg').textContent='تنظیمات ذخیره شد.';refresh()}catch(e){$('setMsg').textContent=e.message}}
function updateDash(){$('dashHost').textContent=settings.node_host||'همان دامنه پنل';$('dashPort').textContent=settings.node_port||'443'}
function toggleUserMenu(force){const m=$('userDropdown'),b=$('userMenuBtn');if(!m)return;const open=typeof force==='boolean'?force:m.classList.contains('hidden');m.classList.toggle('hidden',!open);if(b)b.setAttribute('aria-expanded',String(open))}
function updateUserQuota(used,total){if($('dropQuota'))$('dropQuota').textContent=fmtUsed(used)+' / '+fmtUsed(total);const pct=total?Math.min(100,used/total*100):0;if($('dropQuotaFill'))$('dropQuotaFill').style.width=pct+'%'}
function openMyAccount(){toggleUserMenu(false);openTab('account')}
function showPanelUsage(){toggleUserMenu(false);const total=clients.reduce((n,x)=>n+Number(x.totalBytes||0),0),used=clients.reduce((n,x)=>n+Number(x.usedBytes||x.used||0),0),pct=total?Math.round(used/total*100):0;alert(`حجم مصرفی پنل\n\nمصرف شده: ${fmtUsed(used)}\nحجم کل: ${fmtUsed(total)}\nدرصد مصرف: ${pct}%`)}
async function switchAccount(){toggleUserMenu(false);await req('/api/logout',{method:'POST'});$('app').classList.add('hidden');$('login').classList.remove('hidden');$('password').value='';$('loginMsg').textContent='برای ورود به اکانت دیگر، نام کاربری و رمز آن را وارد کنید.';$('username').focus()}
async function logout(){await req('/api/logout',{method:'POST'});location.reload()}
async function copy(s){s=dec(s);try{await navigator.clipboard.writeText(s);alert('کپی شد')}catch{prompt('مقدار:',s)}}
const enc=s=>btoa(unescape(encodeURIComponent(s))),dec=s=>decodeURIComponent(escape(atob(s))),esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
async function changeAccount(){try{let d=await req('/api/account/change',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:$('accUser').value,oldPassword:$('accOld').value,newPassword:$('accNew').value})});$('accMsg').textContent=d.msg||'ذخیره شد؛ دوباره وارد شوید';setTimeout(()=>location.reload(),1200)}catch(e){$('accMsg').textContent=e.message}}
function permsFromForm(){return{clients_view:$('pView').checked,clients_create:$('pCreate').checked,clients_edit:$('pEdit').checked,clients_delete:$('pDelete').checked,configs_view:$('pSub').checked,dns_view:$('pDns').checked,settings_view:$('pSettings').checked}}
async function createPanel(){try{let d=await req('/api/admin/panels/create',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:$('panelName').value,username:$('panelUser').value,password:$('panelPass').value,allowed_ip:$('panelAllowedIp').value,permissions:permsFromForm()})});$('panelMsg').textContent=`پنل «${d.panel.name}» ساخته شد. IP تشخیص‌داده‌شده: ${d.panel.detected_ip}`;$('panelName').value='';$('panelUser').value='';$('panelPass').value='';loadPanels()}catch(e){$('panelMsg').textContent=e.message}}
async function loadPanels(){if(!me||me.role!=='admin')return;try{let d=await req('/api/admin/panels');$('detectedIp').textContent=d.detected_ip||'نامشخص';$('panelsList').innerHTML=d.panels.length?d.panels.map(p=>`<div class="panel-row"><div><b>${esc(p.name)}</b><small>شناسه ${p.id} · IP ساخت: ${esc(p.detected_ip||'—')} ${p.allowed_ip?`· IP مجاز: ${esc(p.allowed_ip)}`:''}</small></div><div class="row-actions"><span class="tag">${p.enabled?'فعال':'غیرفعال'}</span><button class="mini" onclick="togglePanel(${p.id})">${p.enabled?'غیرفعال':'فعال'}</button><button class="danger mini" onclick="deletePanel(${p.id})">حذف</button></div></div>`).join(''):'<div class="empty">هنوز پنل فرزندی ساخته نشده است.</div>';$('overviewPanels').innerHTML=d.panels.slice(0,4).map(p=>`<div class="mini-card"><b>${esc(p.name)}</b><small>${p.enabled?'فعال':'غیرفعال'} · IP ${esc(p.detected_ip||'—')}</small></div>`).join('')||'<div class="empty">پنل فرزندی وجود ندارد.</div>'}catch(e){$('panelMsg').textContent=e.message}}
async function togglePanel(id){try{await req('/api/admin/panels/'+id+'/toggle',{method:'POST'});loadPanels()}catch(e){alert(e.message)}}
async function deletePanel(id){if(!confirm('این پنل فرزند و اکانت ورودش حذف شود؟'))return;try{await req('/api/admin/panels/'+id+'/delete',{method:'POST'});loadPanels()}catch(e){alert(e.message)}}
async function loadUsers(){try{let d=await req('/api/admin/users');$('usersList').innerHTML=d.users.map(u=>`<div class="client-row"><div><b>${esc(u.username)}</b><small>${u.role==='admin'?'ادمین':(u.panel_id?'کاربر پنل #'+u.panel_id:'کاربر مادر')} · ${u.enabled?'فعال':'غیرفعال'}</small></div><div class="row-actions"><button class="mini" onclick="toggleUser(${u.id})">${u.enabled?'غیرفعال کردن':'فعال کردن'}</button><button class="danger mini" onclick="deleteUser(${u.id})">حذف</button></div></div>`).join('')}catch{}}
async function toggleUser(id){try{await req('/api/admin/users/'+id+'/toggle',{method:'POST'});loadUsers()}catch(e){alert(e.message)}}
async function deleteUser(id){if(!confirm('این اکانت حذف شود؟'))return;try{await req('/api/admin/users/'+id+'/delete',{method:'POST'});loadUsers()}catch(e){alert(e.message)}}
document.addEventListener('change',e=>{if(e.target?.id==='setTheme')applyTheme(e.target.value)});
(async()=>{try{let d=await req('/api/me');if(d.authenticated)showApp()}catch{}})();

document.addEventListener('click',e=>{if(!e.target.closest('.account-menu-wrap'))toggleUserMenu(false)});
