
/* VPNSTAN v26 multilingual UI */
const I18N={
 fa:{dir:'rtl',title:'نمای کلی',sub:'مدیریت سرویس vpnstan · نسخه v26',badgeMaster:'پنل مادر',logout:'خروج',overview:'نمای کلی',clients:'کلاینت‌ها',configs:'کانفیگ‌ها',subscriptions:'اشتراک‌ها',dns:'DNS',settings:'تنظیمات',account:'حساب من',admin:'مدیریت پنل‌ها',online:'سرویس آنلاین',login:'ورود به پنل',loginDesc:'مدیریت مستقل کانفیگ‌ها، اشتراک‌ها و پنل‌های فرزند',username:'نام کاربری',password:'رمز عبور'},
 en:{dir:'ltr',title:'Overview',sub:'vpnstan service management · v26',badgeMaster:'Master Panel',logout:'Logout',overview:'Overview',clients:'Clients',configs:'Configs',subscriptions:'Subscriptions',dns:'DNS',settings:'Settings',account:'My Account',admin:'Panel Management',online:'Service Online',login:'Sign in',loginDesc:'Independent management of configs, subscriptions and child panels',username:'Username',password:'Password'}
};
let currentLang=localStorage.getItem('vpnstan_lang')||'fa';
function setLanguage(lang){currentLang=lang==='en'?'en':'fa';localStorage.setItem('vpnstan_lang',currentLang);document.documentElement.lang=currentLang;document.documentElement.dir=I18N[currentLang].dir;const t=I18N[currentLang];
 const set=(sel,key)=>{const e=document.querySelector(sel);if(e)e.textContent=t[key]};
 set('#title','title');set('header small','sub');set('#currentPanelBadge','badgeMaster');
 const navMap={dashboard:'overview',clients:'clients',configs:'configs',subscriptions:'subscriptions',dns:'dns',settings:'settings',account:'account',admin:'admin'};
 document.querySelectorAll('.nav[data-tab]').forEach(n=>{const k=navMap[n.dataset.tab]; if(k){let small=n.querySelector('small'); const txt=t[k]; if(small){n.childNodes[0].textContent=({dashboard:'◈ ',clients:'◉ ',configs:'⌁ ',subscriptions:'↗ ',dns:'◉ ',settings:'⚙ ',account:'👤 ',admin:'🛡 '}[n.dataset.tab]||'')+txt+' '; small.textContent=n.dataset.tab==='dashboard'?'Overview':'';}else{n.textContent=txt;}}});
 const logout=document.querySelector('button[onclick="logout()"]');if(logout)logout.textContent=t.logout;
 const loginTitle=document.querySelector('#login h1');if(loginTitle)loginTitle.textContent=t.login;
 const loginP=document.querySelector('#login p');if(loginP)loginP.textContent=t.loginDesc;
 const u=document.querySelector('#username');if(u)u.placeholder=t.username; const p=document.querySelector('#password');if(p)p.placeholder=t.password;
 const ls=document.querySelector('#langSelect');if(ls)ls.value=currentLang;
 document.querySelectorAll('.login-lang button').forEach(b=>b.textContent=currentLang==='fa'?'🌐 فارسی / English':'🌐 English / فارسی');
 // Keep form controls and API behavior intact; translate only stable labels/placeholders.
 const labels={
 '#name':['نام کلاینت','Client name'],'#gb':['حجم هر کانفیگ (GB)','Traffic per config (GB)'],'#days':['اعتبار هر کانفیگ (روز)','Validity (days)'],'#subCount':['تعداد کانفیگ در یک ساب','Configs per subscription'],
 '#setHost':['دامنه / Host نود','Node domain / Host'],'#setPort':['پورت اتصال','Connection port'],'#setPath':['مسیر VLESS WebSocket','VLESS WebSocket path'],'#setVmessPath':['مسیر VMess WebSocket','VMess WebSocket path'],'#setSub':['مسیر Subscription','Subscription path'],'#setTitle':['عنوان اشتراک','Subscription title'],'#setSupport':['لینک پشتیبانی','Support link'],'#setWgEndpoint':['WireGuard Endpoint','WireGuard Endpoint'],'#setWgKey':['WireGuard Server Public Key','WireGuard Server Public Key']};
 Object.entries(labels).forEach(([sel,v])=>{const e=document.querySelector(sel);if(e){e.placeholder=v[currentLang==='fa'?0:1]||e.placeholder;const l=e.previousElementSibling;if(l&&l.tagName==='LABEL')l.textContent=v[currentLang==='fa'?0:1]}});
}
window.addEventListener('DOMContentLoaded',()=>{const ls=document.getElementById('langSelect');if(ls)ls.addEventListener('change',e=>setLanguage(e.target.value));setLanguage(currentLang)});

const $=id=>document.getElementById(id);let clients=[],settings={},me=null;
function applyTheme(t){t=t||'dark';document.documentElement.setAttribute('data-theme',t);localStorage.setItem('vpnstan_theme',t);if($('setTheme'))$('setTheme').value=t}
applyTheme(localStorage.getItem('vpnstan_theme')||'dark');
async function req(u,o={}){let r=await fetch(u,{credentials:'include',...o});let d;try{d=await r.json()}catch{d={msg:'خطای پاسخ سرور'}}if(!r.ok)throw Error(d.msg||'خطا');return d}
const titles={dashboard:'نمای کلی',clients:'کلاینت‌ها',configs:'کانفیگ‌ها',subscriptions:'اشتراک‌ها',dns:'DNS',settings:'تنظیمات',account:'حساب من',admin:'مدیریت پنل‌ها'};
function can(p){return !me||me.role==='admin'||me.panel_id===0||p==='overview'||p==='account'||me.permissions?.[p]}
function applyPermissions(){document.querySelectorAll('.nav[data-perm]').forEach(n=>{const p=n.dataset.perm;n.classList.toggle('hidden',p==='admin'?! (me?.role==='admin'):!can(p))});if(me?.role==='admin'){document.getElementById('adminNav').classList.remove('hidden');$('masterOverview').classList.remove('hidden')}else{$('masterOverview').classList.add('hidden')}$('currentPanelBadge').textContent=me?.panel_id?'پنل فرزند #'+me.panel_id:'پنل مادر'}
function openTab(id){const section=$(id);if(!section)return;const nav=document.querySelector(`.nav[data-tab="${id}"]`);if(nav&&nav.classList.contains('hidden'))return;document.querySelectorAll('.tab').forEach(x=>x.classList.add('hidden'));section.classList.remove('hidden');document.querySelectorAll('.nav').forEach(x=>x.classList.toggle('active',x.dataset.tab===id));$('title').textContent=titles[id]||id;if(id==='clients')renderClients();if(id==='configs')renderConfigs();if(id==='subscriptions')renderSubs();if(id==='dns')renderDns();if(id==='settings')loadSettings();if(id==='account')loadMe();if(id==='admin')loadPanels()}
document.querySelectorAll('.nav').forEach(x=>x.addEventListener('click',()=>openTab(x.dataset.tab)));
window.addEventListener('error',e=>{const el=$('loginMsg')||$('createMsg');if(el&&!e.message.includes('Script error'))el.textContent='خطای رابط پنل: '+e.message});
function updateProtocolFields(){const p=$('protocol')?.value;const f=$('dnsField');if(f){f.classList.add('hidden');f.innerHTML=''}const note=$('createMsg');if(note&&p==='dns')note.textContent='برای این کاربر یک DNS اختصاصی DoH با حجم و اعتبار جداگانه ساخته می‌شود.';else if(note&&note.textContent.includes('DNS اختصاصی'))note.textContent=''}
$('protocol')?.addEventListener('change',updateProtocolFields);window.addEventListener('DOMContentLoaded',updateProtocolFields);
async function login(){try{let d=await req('/api/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:$('username').value,password:$('password').value})});if(!d.success)throw Error(d.msg);showApp()}catch(e){$('loginMsg').textContent=e.message}}
let liveRefreshTimer=null;async function showApp(){$('login').classList.add('hidden');$('app').classList.remove('hidden');await loadMe();await loadSettings();await refresh();if(!liveRefreshTimer)liveRefreshTimer=setInterval(()=>refresh(),10000)}
async function refresh(){try{let d=await req('/api/clients');clients=d.clients;$('count').textContent=clients.length;$('active').textContent=clients.filter(x=>x.enabled&&!expired(x)).length;$('expired').textContent=clients.filter(expired).length;renderClients();renderConfigs();renderSubs();renderDns();updateDash()}catch(e){if(e.message.includes('ورود'))location.reload()}}
function expired(c){return c.expiryAt&&c.expiryAt*1000<Date.now()}
async function loadMe(){try{let d=await req('/api/me');me=d.user;if(!me)return;applyPermissions();$('accUser').value=me.username;if(me.role==='admin')loadPanels()}catch{}}
function fmtUsed(n){n=Number(n||0);const u=['B','KB','MB','GB','TB'];let i=0,x=n;while(x>=1024&&i<u.length-1){x/=1024;i++}return(i>=3?x.toFixed(2):Math.round(x*100)/100)+' '+u[i]}
function renderClients(){if(!$('clientsList'))return;$('clientsList').innerHTML=clients.length?clients.map(c=>{const used=Number(c.used||0),total=Number(c.totalBytes||0),pct=total?Math.min(100,used/total*100):0,cls=pct>=95?'danger':pct>=80?'warn':'';return `<div class="client-row"><div class="client-meta"><b>${esc(c.name)}</b><small>${c.protocol.toUpperCase()} · ${c.gb} GB · ${c.days} روز · ${expired(c)?'منقضی':(c.online?'آنلاین':'فعال')}</small></div><div class="usage"><div class="usage-top"><span>مصرف</span><strong>${esc(c.usedText||fmtUsed(used))} / ${esc(c.totalText||fmtUsed(total))} · ${pct.toFixed(1)}%</strong></div><div class="usage-bar"><div class="usage-fill ${cls}" style="width:${pct}%"></div></div></div><div class="row-actions">${can('clients_edit')?`<button class="mini" onclick="editClient(${c.id})">ویرایش</button>`:''}<button class="mini" onclick="copy('${enc(c.config)}')">کپی ${esc(c.protocol.toUpperCase())}</button>${can('configs_view')?`<button class="mini" onclick="copy('${enc(c.subscription)}')">کپی Sub</button>`:''}${can('clients_delete')?`<button class="danger mini" onclick="del(${c.id})">حذف</button>`:''}</div></div>`}).join(''):'<div class="empty">هنوز کلاینتی ساخته نشده است.</div>'}
function renderConfigs(){if(!$('configList'))return;$('configList').innerHTML=clients.length?clients.map(c=>`<div class="config-card"><div class="config-top"><div><b>${esc(c.name)}</b><span class="tag">${esc(c.protocol.toUpperCase())} · ${expired(c)?'منقضی':'فعال'}</span></div><small>${c.gb} GB · تا ${new Date(c.expiryAt*1000).toLocaleDateString('fa-IR')}</small></div><label>کانفیگ ${esc(c.protocol.toUpperCase())}</label><div class="copybox"><code>${esc(c.config)}</code><button onclick="copy('${enc(c.config)}')">کپی</button></div>${c.protocol==='dns'?`<label>DNS Subscription اختصاصی</label><div class="copybox"><code>${esc(c.dnsSubscription||'')}</code><button onclick="copy('${enc(c.dnsSubscription||'')}')">کپی</button></div><label>DNS اختصاصی DoH</label><div class="copybox"><code>${esc(c.dnsUrl||'')}</code><button onclick="copy('${enc(c.dnsUrl||'')}')">کپی</button></div>`:(c.protocol==='vless'||c.protocol==='vmess'?`<label>Subscription</label><div class="copybox"><code>${esc(c.subscription||'')}</code><button onclick="copy('${enc(c.subscription||'')}')">کپی</button></div>`:'')}<div class="config-actions">${can('clients_edit')?`<button class="mini" onclick="editClient(${c.id})">ویرایش</button>`:''}${can('clients_delete')?`<button class="danger mini" onclick="del(${c.id})">حذف</button>`:''}</div></div>`).join(''):'<div class="empty">برای نمایش کانفیگ، ابتدا یک کلاینت بسازید.</div>'}
function renderSubs(){if(!$('subList'))return;const groups={};clients.filter(c=>c.protocol==='vless'||c.protocol==='vmess').forEach(c=>(groups[c.subId||c.subscription||c.id]??=[]).push(c));const vals=Object.entries(groups);$('subList').innerHTML=vals.length?vals.map(([sid,arr])=>{const total=arr.reduce((n,c)=>n+Number(c.totalBytes||0),0),used=arr.reduce((n,c)=>n+Number(c.usedBytes||0),0),pct=total?Math.min(100,Math.round(used/total*100)):0;return `<article class="sub-card"><div class="sub-head"><div class="sub-brand"><div class="sub-icon">↯</div><div><b>Subscription</b><span>${arr.length} کانفیگ · ${esc(arr[0].name||'VPNSTAN')}</span></div></div><span class="sub-status">فعال</span></div><div class="sub-summary"><div><small>تعداد کانفیگ</small><strong>${arr.length}</strong></div><div><small>مصرف کل</small><strong>${esc(fmtUsed(used))}</strong></div><div><small>حجم کل</small><strong>${esc(fmtUsed(total))}</strong></div></div><div class="sub-progress"><div><span>مصرف اشتراک</span><b>${pct}%</b></div><i><em style="width:${pct}%"></em></i></div><label>لینک اشتراک</label><div class="copybox sub-link"><code>${esc(arr[0].subscription||'')}</code><button onclick="copy('${enc(arr[0].subscription||'')}')">کپی لینک</button></div><div class="sub-items">${arr.map((c,i)=>`<div class="sub-item"><div class="sub-number">${i+1}</div><div><b>${esc(c.name)}</b><small>${c.protocol.toUpperCase()} · ${esc(c.usedText||'0 B')} / ${esc(c.totalText||fmtUsed(c.totalBytes))}</small></div><span class="sub-dot"></span></div>`).join('')}</div></article>`}).join(''):'<div class="empty">هنوز Subscription ساخته نشده است.</div>'}
function renderDns(){if(!$('dnsList'))return;const vals=clients.filter(c=>c.protocol==='dns');$('dnsList').innerHTML=vals.length?vals.map(c=>`<div class="config-card"><div class="config-top"><div><b>${esc(c.name)}</b><span class="tag">DNS اختصاصی</span></div><small>${esc(c.remainingText||'')}</small></div><label>Custom DoH برای DNS Changer</label><div class="copybox"><code>${esc(c.dnsUrl||'')}</code><button onclick="copy('${enc(c.dnsUrl||'')}')">کپی</button></div><label>Subscription</label><div class="copybox"><code>${esc(c.dnsSubscription||'')}</code><button onclick="copy('${enc(c.dnsSubscription||'')}')">کپی</button></div><div class="usage-top"><span>مصرف</span><strong>${esc(c.usedText||'0 B')} / ${esc(c.totalText||fmtUsed(c.totalBytes))}</strong></div></div>`).join(''):'<div class="empty">DNS اختصاصی ساخته نشده است.</div>'}
async function createClient(){let name=$('name').value.trim(),gb=+$('gb').value,days=+$('days').value,protocol=$('protocol').value,subCount=Math.floor(+$('subCount').value||1);if(!name||gb<=0||days<=0||subCount<1||subCount>20)return $('createMsg').textContent='نام، حجم، مدت و تعداد کانفیگ را درست وارد کنید.';if(protocol==='dns'&&subCount>1)return $('createMsg').textContent='برای DNS تعداد کانفیگ در هر ساب باید 1 باشد.';try{let d=await req('/api/clients/create',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name,gb,days,protocol,dnsServer:'',subCount})});$('createMsg').textContent=`${d.count||subCount} کانفیگ داخل یک ساب ساخته شد.`;$('name').value='';$('subCount').value='1';await refresh();openTab(protocol==='dns'?'dns':'subscriptions');setTimeout(()=>copy(protocol==='dns'?d.client.dnsUrl:d.client.subscription),100)}catch(e){$('createMsg').textContent=e.message||'ساخت کانفیگ انجام نشد'}}
function editClient(id){const c=clients.find(x=>Number(x.id)===Number(id));if(!c)return;$('editId').value=c.id;$('editName').value=c.name;$('editProtocol').value=c.protocol;$('editGb').value=c.gb;$('editDays').value=c.days;$('editMsg').textContent='';$('editModal').classList.remove('hidden')}
function closeEdit(){$('editModal').classList.add('hidden')}
async function saveEdit(){try{const id=$('editId').value;await req('/api/clients/'+id+'/edit',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:$('editName').value,protocol:$('editProtocol').value,gb:$('editGb').value,days:$('editDays').value})});$('editMsg').textContent='تغییرات ذخیره شد.';await refresh();setTimeout(closeEdit,400)}catch(e){$('editMsg').textContent=e.message}}
async function del(id){if(!confirm('این کلاینت حذف شود؟'))return;try{await req('/api/clients/'+id+'/delete',{method:'POST'});refresh()}catch(e){alert(e.message)}}
async function loadSettings(){try{let d=await req('/api/settings');settings=d.settings;$('setHost').value=settings.node_host||'';$('setPort').value=settings.node_port||443;$('setPath').value=settings.ws_path||'/ws';$('setVmessPath').value=settings.vmess_path||'/vmess';$('setSub').value=settings.sub_path||'sub';$('setTitle').value=settings.panel_title||'vpnstan';$('setTheme').value=settings.theme||localStorage.getItem('vpnstan_theme')||'dark';applyTheme($('setTheme').value);$('setSupport').value=settings.support_url||'';$('setWgEndpoint').value=settings.wg_endpoint||'';$('setWgKey').value=settings.wg_server_public_key||'';updateDash()}catch(e){}}
async function saveSettings(){try{let d=await req('/api/settings',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({node_host:$('setHost').value,node_port:$('setPort').value,ws_path:$('setPath').value,vmess_path:$('setVmessPath').value,sub_path:$('setSub').value,panel_title:$('setTitle').value,support_url:$('setSupport').value,theme:$('setTheme').value,wg_endpoint:$('setWgEndpoint').value,wg_server_public_key:$('setWgKey').value})});settings=d.settings;applyTheme(settings.theme||'dark');$('setMsg').textContent='تنظیمات ذخیره شد.';refresh()}catch(e){$('setMsg').textContent=e.message}}
function updateDash(){$('dashHost').textContent=settings.node_host||'همان دامنه پنل';$('dashPort').textContent=settings.node_port||'443'}
async function logout(){await req('/api/logout',{method:'POST'});location.reload()}
async function copy(s){s=dec(s);try{await navigator.clipboard.writeText(s);alert('کپی شد')}catch{prompt('مقدار:',s)}}
const enc=s=>btoa(unescape(encodeURIComponent(s))),dec=s=>decodeURIComponent(escape(atob(s))),esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
async function changeAccount(){try{let d=await req('/api/account/change',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:$('accUser').value,oldPassword:$('accOld').value,newPassword:$('accNew').value})});$('accMsg').textContent=d.msg||'ذخیره شد؛ دوباره وارد شوید';setTimeout(()=>location.reload(),1200)}catch(e){$('accMsg').textContent=e.message}}
function permsFromForm(){return{clients_view:$('pView').checked,clients_create:$('pCreate').checked,clients_edit:$('pEdit').checked,clients_delete:$('pDelete').checked,configs_view:$('pSub').checked,dns_view:$('pDns').checked,settings_view:$('pSettings').checked}}
async function createPanel(){try{let d=await req('/api/admin/panels/create',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:$('panelName').value,username:$('panelUser').value,password:$('panelPass').value,allowed_ip:$('panelAllowedIp').value,permissions:permsFromForm()})});$('panelMsg').textContent=`پنل «${d.panel.name}» ساخته شد. IP تشخیص‌داده‌شده: ${d.panel.detected_ip}`;$('panelName').value='';$('panelUser').value='';$('panelPass').value='';loadPanels()}catch(e){$('panelMsg').textContent=e.message}}
async function loadPanels(){if(!me||me.role!=='admin')return;try{let d=await req('/api/admin/panels');$('detectedIp').textContent=d.detected_ip||'نامشخص';$('panelsList').innerHTML=d.panels.length?d.panels.map(p=>`<div class="panel-row"><div><b>${esc(p.name)}</b><small>شناسه ${p.id} · IP ساخت: ${esc(p.detected_ip||'—')} ${p.allowed_ip?`· IP مجاز: ${esc(p.allowed_ip)}`:''}</small></div><div class="row-actions"><span class="tag">${p.enabled?'فعال':'غیرفعال'}</span><button class="mini" onclick="togglePanel(${p.id})">${p.enabled?'غیرفعال':'فعال'}</button><button class="danger mini" onclick="deletePanel(${p.id})">حذف</button></div></div>`).join(''):'<div class="empty">هنوز پنل فرزندی ساخته نشده است.</div>';$('overviewPanels').innerHTML=d.panels.slice(0,4).map(p=>`<div class="mini-card"><b>${esc(p.name)}</b><small>${p.enabled?'فعال':'غیرفعال'} · IP ${esc(p.detected_ip||'—')}</small></div>`).join('')||'<div class="empty">پنل فرزندی وجود ندارد.</div>'}catch(e){$('panelMsg').textContent=e.message}}
async function togglePanel(id){try{await req('/api/admin/panels/'+id+'/toggle',{method:'POST'});loadPanels()}catch(e){alert(e.message)}}
async function deletePanel(id){if(!confirm('این پنل فرزند و اکانت ورودش حذف شود؟'))return;try{await req('/api/admin/panels/'+id+'/delete',{method:'POST'});loadPanels()}catch(e){alert(e.message)}}
async function loadUsers(){try{let d=await req('/api/admin/users');$('usersList').innerHTML=d.users.map(u=>`<div class="client-row"><div><b>${esc(u.username)}</b><small>${u.role==='admin'?'ادمین':(u.panel_id?'کاربر پنل #'+u.panel_id:'کاربر مادر')} · ${u.enabled?'فعال':'غیرفعال'}</small></div><div class="row-actions"><button class="mini" onclick="toggleUser(${u.id})">${u.enabled?'غیرفعال کردن':'فعال کردن'}</button><button class="danger mini" onclick="deleteUser(${u.id})">حذف</button></div></div>`).join('')}catch{}}
async function toggleUser(id){try{await req('/api/admin/users/'+id+'/toggle',{method:'POST'});loadUsers()}catch(e){alert(e.message)}}
async function deleteUser(id){if(!confirm('این اکانت حذف شود؟'))return;try{await req('/api/admin/users/'+id+'/delete',{method:'POST'});loadUsers()}catch(e){alert(e.message)}}
document.addEventListener('change',e=>{if(e.target?.id==='setTheme')applyTheme(e.target.value)});
(async()=>{try{let d=await req('/api/me');if(d.authenticated)showApp()}catch{}})();
