const $=id=>document.getElementById(id);let clients=[],settings={},me=null,editOriginal=null;
function applyTheme(t){t=t||'dark';document.documentElement.setAttribute('data-theme',t);localStorage.setItem('vpnstan_theme',t);if($('setTheme'))$('setTheme').value=t}
applyTheme(localStorage.getItem('vpnstan_theme')||'dark');
async function req(u,o={}){let r=await fetch(u,{credentials:'include',cache:'no-store',...o});let d={};try{d=await r.json()}catch{}if(!r.ok)throw Error(d.msg||d.error||'خطا');return d}
function openTab(id){document.querySelectorAll('.tab').forEach(x=>x.classList.add('hidden'));const target=$(id);if(target)target.classList.remove('hidden');document.querySelectorAll('.nav').forEach(x=>x.classList.toggle('active',x.dataset.tab===id));const t={dashboard:'داشبورد',clients:'کلاینت‌ها',configs:'اشتراک‌ها و کانفیگ‌ها',settings:'تنظیمات',account:'حساب من',admin:'مدیریت ادمین'}[id]||'VPNSTAN';$('title').textContent=t;if(id==='configs')renderConfigs()}
document.querySelectorAll('.nav').forEach(x=>x.onclick=()=>openTab(x.dataset.tab));
function updateProtocolFields(){const p=$('protocol')?.value;const tr=$('transport');const sc=$('subCount');if(tr){const restricted=p==='dns'||p==='wireguard';tr.disabled=restricted;if(restricted)tr.value='ws'}if(sc){const restricted=p==='dns'||p==='wireguard';sc.disabled=restricted;if(restricted)sc.value='1'}const note=$('createMsg');if(note&&p==='dns')note.textContent='برای DNS فعلاً یک کانفیگ در هر Subscription ساخته می‌شود.';else if(note&&p==='wireguard')note.textContent='WireGuard فقط با Endpoint واقعی UDP قابل اتصال است.';else if(note&&/DNS|WireGuard/.test(note.textContent))note.textContent=''}
$('protocol')?.addEventListener('change',updateProtocolFields);window.addEventListener('DOMContentLoaded',updateProtocolFields);
async function login(){try{let d=await req('/api/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:$('username').value,password:$('password').value})});if(!d.success)throw Error(d.msg);showApp()}catch(e){$('loginMsg').textContent=e.message}}
let liveRefreshTimer=null;function showApp(){$('login').classList.add('hidden');$('app').classList.remove('hidden');refresh();loadSettings();loadMe();if(!liveRefreshTimer)liveRefreshTimer=setInterval(refresh,3000)}
function expired(c){return c.expiryAt&&c.expiryAt*1000<Date.now()}
function subGroups(){const m=new Map();clients.forEach(c=>{const key=c.subId||('client-'+c.id);if(!m.has(key))m.set(key,[]);m.get(key).push(c)});return [...m.entries()].map(([id,items])=>({id,items}))}
async function refresh(){try{const d=await req('/api/clients');clients=d.clients||[];$('count').textContent=clients.length;$('subCountDash').textContent=subGroups().length;$('active').textContent=clients.filter(x=>x.enabled&&!expired(x)).length;$('expired')&&($('expired').textContent=clients.filter(expired).length);renderClients();renderConfigs();updateDash()}catch(e){if(String(e.message).includes('ورود'))location.reload()}}
async function loadMe(){try{let d=await req('/api/me');me=d.user;if(me){$('accUser').value=me.username;$('adminNav').classList.toggle('hidden',me.role!=='admin');if(me.role==='admin')loadUsers()}}catch{}}
function fmtUsed(n){n=Number(n||0);const u=['B','KB','MB','GB','TB'];let i=0,x=n;while(x>=1024&&i<u.length-1){x/=1024;i++}return (i>=3?x.toFixed(2):Math.round(x*100)/100)+' '+u[i]}
function renderClients(){
  $('clientsList').innerHTML=clients.length?clients.map(c=>{const used=Number(c.used||0),total=Number(c.totalBytes||0),pct=total?Math.min(100,used/total*100):0;const cls=pct>=95?'danger':pct>=80?'warn':'';const status=expired(c)?'منقضی':(c.online?'آنلاین':'فعال');const statusCls=expired(c)?'expired':(c.online?'online':'');return `<article class="client-row"><div class="client-meta"><div class="client-name-line"><span class="client-avatar">${esc((c.name||'V').slice(0,1).toUpperCase())}</span><div><b>${esc(c.name)}</b><div class="client-tags"><span>${esc(c.protocol.toUpperCase())}</span><span>${esc((c.transport||'ws').toUpperCase())}</span><span>ساب: ${esc((c.subId||'').slice(0,8))}</span><em class="client-status ${statusCls}">● ${status}</em></div></div></div></div><div class="usage"><div class="usage-top"><span>مصرف</span><strong>${esc(c.usedText||fmtUsed(used))} / ${esc(c.totalText||fmtUsed(total))}</strong></div><div class="usage-bar"><div class="usage-fill ${cls}" style="width:${pct}%"></div></div><div class="usage-foot"><span>${pct.toFixed(1)}%</span><span>انقضا: ${esc(c.expiryText||'—')}</span></div></div><div class="row-actions"><button type="button" class="mini primary-mini" onclick="editClient(${c.id})">ویرایش</button><button type="button" class="mini" onclick="copy('${enc(c.config)}')">کپی</button><button type="button" class="mini" onclick="copy('${enc(c.subscription)}')">Sub</button><button type="button" class="mini danger" onclick="del(${c.id})">حذف</button></div></article>`}).join(''):'<div class="empty">هنوز کلاینتی ساخته نشده است.</div>'
}
function renderConfigs(){
  const groups=subGroups();
  $('configList').innerHTML=groups.length?groups.map((g,gi)=>{const first=g.items[0],total=g.items.reduce((a,c)=>a+Number(c.totalBytes||0),0),used=g.items.reduce((a,c)=>a+Number(c.used||0),0),pct=total?Math.min(100,used/total*100):0;const online=g.items.some(c=>c.online&&!expired(c));const sub=first.subscription||'';return `<article class="subscription-group"><div class="sub-group-head"><div><div class="sub-eyebrow">SUBSCRIPTION ${gi+1}</div><h2>${esc(first.name.replace(/-\d+$/,''))}</h2><div class="sub-meta"><span>${g.items.length} کانفیگ</span><span>${esc(first.protocol.toUpperCase())}</span><span>${esc(first.subId||'')}</span></div></div><div class="sub-state ${online?'online':''}">● ${online?'آنلاین':'آفلاین'}</div></div><div class="sub-summary"><div><small>حجم مجموع</small><b>${fmtUsed(total)}</b></div><div><small>مصرف مجموع</small><b>${fmtUsed(used)}</b></div><div><small>باقی‌مانده</small><b>${fmtUsed(Math.max(0,total-used))}</b></div><div><small>درصد مصرف</small><b>${pct.toFixed(1)}%</b></div></div><div class="usage-bar big"><div class="usage-fill" style="width:${pct}%"></div></div><div class="sub-link"><code>${esc(sub)}</code><button onclick="copy('${enc(sub)}')">کپی ساب</button></div><div class="group-configs">${g.items.map((c,i)=>{const cu=Number(c.used||0),ct=Number(c.totalBytes||0),cp=ct?Math.min(100,cu/ct*100):0;return `<div class="group-config"><div class="group-config-title"><span class="num">${String(i+1).padStart(2,'0')}</span><div><b>${esc(c.name)}</b><div class="client-tags"><span>${esc(c.protocol.toUpperCase())}</span><span>${esc((c.transport||'ws').toUpperCase())}</span></div></div><button class="mini primary-mini" onclick="editClient(${c.id})">ویرایش</button></div><div class="usage-top"><span>${esc(c.usedText||fmtUsed(cu))} / ${esc(c.totalText||fmtUsed(ct))}</span><span>${cp.toFixed(1)}%</span></div><div class="usage-bar"><div class="usage-fill" style="width:${cp}%"></div></div><div class="group-config-actions"><button class="mini" onclick="copy('${enc(c.config)}')">کپی کانفیگ</button><button class="mini" onclick="copy('${enc(sub)}')">کپی Subscription</button></div></div>`}).join('')}</div><div class="sub-actions"><button class="btn primary" onclick="copy('${enc(sub)}')">کپی لینک اشتراک</button><a class="ghost" target="_blank" href="${esc(sub)}?html=1&v=25">نمایش صفحه ساب</a></div></article>`}).join(''):'<div class="empty">برای نمایش Subscription ابتدا یک کانفیگ بسازید.</div>'
}
async function createClient(){const name=$('name').value.trim(),gb=+$('gb').value,days=+$('days').value,protocol=$('protocol').value,transport=$('transport').value,subCount=Math.floor(+$('subCount').value||1);if(!name||gb<=0||days<=0||subCount<1||subCount>20){$('createMsg').textContent='نام، حجم، مدت و تعداد کانفیگ را درست وارد کنید.';return}if((protocol==='dns'||protocol==='wireguard')&&subCount>1){$('createMsg').textContent='این نوع سرویس فعلاً فقط یک کانفیگ در هر ساب دارد.';return}try{const d=await req('/api/clients/create',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name,gb,days,protocol,transport,subCount})});$('createMsg').textContent=`✓ ${d.count||subCount} کانفیگ با یک Subscription ساخته شد.`;await refresh();openTab('configs');setTimeout(()=>copy(protocol==='dns'?d.client.dnsUrl:d.client.subscription),100)}catch(e){$('createMsg').textContent=e.message}}
function editClient(id){const c=clients.find(x=>Number(x.id)===Number(id));if(!c){toast('کانفیگ پیدا نشد','error');return}editOriginal={...c};$('editId').value=c.id;$('editName').value=c.name||'';$('editProtocol').value=c.protocol||'vless';$('editTransport').value=c.transport||'ws';$('editGb').value=c.gb;$('editDays').value=c.days;updateEditFields();$('editMsg').textContent='';$('editMsg').className='msg';$('editModal').classList.remove('hidden');document.body.classList.add('modal-open');setTimeout(()=>$('editName').focus(),60)}
function updateEditFields(){const p=$('editProtocol')?.value,tr=$('editTransport');if(!tr)return;const restricted=p==='dns'||p==='wireguard';tr.disabled=restricted;if(restricted)tr.value='ws'}
function closeEdit(){const m=$('editModal');if(m)m.classList.add('hidden');document.body.classList.remove('modal-open');editOriginal=null}
async function saveEdit(){const btn=document.querySelector('#editModal .save-edit');const msg=$('editMsg');try{const id=Number($('editId').value),name=$('editName').value.trim(),gb=Number($('editGb').value),days=Number($('editDays').value),protocol=$('editProtocol').value,transport=$('editTransport').value;if(!id||!name||gb<=0||days<=0){msg.textContent='نام، حجم و اعتبار را درست وارد کنید.';msg.className='msg error';return}btn.disabled=true;btn.textContent='در حال ذخیره…';const d=await req('/api/clients/'+id+'/edit',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name,protocol,transport,gb,days})});if(!d.success)throw Error(d.msg||'ذخیره ناموفق بود');msg.textContent='✓ تغییرات ذخیره شد';msg.className='msg success';await refresh();toast('کانفیگ با موفقیت ویرایش شد');setTimeout(closeEdit,650)}catch(e){msg.textContent=e.message||'ذخیره تغییرات ناموفق بود';msg.className='msg error'}finally{btn.disabled=false;btn.textContent='ذخیره تغییرات'}}
$('editProtocol')?.addEventListener('change',updateEditFields);document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!$('editModal').classList.contains('hidden'))closeEdit()});document.addEventListener('click',e=>{if(e.target.id==='editModal')closeEdit()});
window.editClient=editClient;window.saveEdit=saveEdit;window.closeEdit=closeEdit;window.createClient=createClient;window.openTab=openTab;
function toast(message,type='ok'){const t=document.createElement('div');t.className='toast '+type;t.textContent=message;document.body.appendChild(t);setTimeout(()=>t.classList.add('show'),10);setTimeout(()=>{t.classList.remove('show');setTimeout(()=>t.remove(),250)},1800)}
async function del(id){if(!confirm('این کلاینت حذف شود؟'))return;try{await req('/api/clients/'+id+'/delete',{method:'POST'});toast('حذف شد');refresh()}catch(e){toast(e.message,'error')}}
async function loadSettings(){try{const d=await req('/api/settings');settings=d.settings;$('setHost').value=settings.node_host||'';$('setPort').value=settings.node_port||443;$('setPath').value=settings.ws_path||'/ws';$('setVmessPath').value=settings.vmess_path||'/vmess';$('setXhttpPath').value=settings.xhttp_path||'/xhttp';$('setGrpcService').value=settings.grpc_service||'vpnstan';$('setGrpcPath').value=settings.grpc_path||'/grpc';$('setUpgradePath').value=settings.httpupgrade_path||'/upgrade';$('setSub').value=settings.sub_path||'sub';$('setTitle').value=settings.panel_title||'vpnstan';$('setTheme').value=settings.theme||localStorage.getItem('vpnstan_theme')||'dark';applyTheme($('setTheme').value);$('setSupport').value=settings.support_url||'';$('setWgEndpoint').value=settings.wg_endpoint||'';$('setWgKey').value=settings.wg_server_public_key||'';updateDash()}catch{}}
async function saveSettings(){try{const d=await req('/api/settings',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({node_host:$('setHost').value,node_port:$('setPort').value,ws_path:$('setPath').value,vmess_path:$('setVmessPath').value,xhttp_path:$('setXhttpPath').value,grpc_service:$('setGrpcService').value,grpc_path:$('setGrpcPath').value,httpupgrade_path:$('setUpgradePath').value,sub_path:$('setSub').value,panel_title:$('setTitle').value,support_url:$('setSupport').value,theme:$('setTheme').value,wg_endpoint:$('setWgEndpoint').value,wg_server_public_key:$('setWgKey').value})});settings=d.settings;applyTheme(settings.theme||'dark');$('setMsg').textContent='تنظیمات ذخیره شد.';refresh()}catch(e){$('setMsg').textContent=e.message}}
function updateDash(){$('dashHost').textContent=settings.node_host||'همان دامنه پنل';$('dashPort').textContent=settings.node_port||'443'}
async function logout(){await req('/api/logout',{method:'POST'});location.reload()}
async function copy(s){s=dec(s);try{await navigator.clipboard.writeText(s);toast('کپی شد ✓')}catch{prompt('مقدار:',s)}}
const enc=s=>btoa(unescape(encodeURIComponent(String(s)))),dec=s=>decodeURIComponent(escape(atob(s))),esc=s=>String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));window.copy=copy;window.del=del;
(async()=>{try{const d=await req('/api/me');if(d.authenticated)showApp()}catch{}})();

async function changeAccount(){try{let d=await req('/api/account/change',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:$('accUser').value,oldPassword:$('accOld').value,newPassword:$('accNew').value})});$('accMsg').textContent=d.msg||'ذخیره شد؛ دوباره وارد شوید';setTimeout(()=>location.reload(),1200)}catch(e){$('accMsg').textContent=e.message}}
async function loadUsers(){try{let d=await req('/api/admin/users');$('usersList').innerHTML=d.users.map(u=>`<div class="client-row"><div><b>${esc(u.username)}</b><small>${u.role==='admin'?'ادمین':'کاربر'} · ${u.enabled?'فعال':'غیرفعال'}</small></div><div class="row-actions"><button class="mini" onclick="toggleUser(${u.id})">${u.enabled?'غیرفعال کردن':'فعال کردن'}</button><button class="danger mini" onclick="deleteUser(${u.id})">حذف</button></div></div>`).join('')}catch(e){}}
async function createUser(){try{let d=await req('/api/admin/users/create',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:$('newUser').value,password:$('newPass').value,role:$('newRole').value})});$('adminMsg').textContent='اکانت ساخته شد.';$('newUser').value='';$('newPass').value='';loadUsers()}catch(e){$('adminMsg').textContent=e.message}}
async function toggleUser(id){try{await req('/api/admin/users/'+id+'/toggle',{method:'POST'});loadUsers()}catch(e){alert(e.message)}}
async function deleteUser(id){if(!confirm('این اکانت حذف شود؟'))return;try{await req('/api/admin/users/'+id+'/delete',{method:'POST'});loadUsers()}catch(e){alert(e.message)}}

document.addEventListener('change',e=>{if(e.target&&e.target.id==='setTheme')applyTheme(e.target.value)});
